# Generated by Django 2.0.8 on 2018-10-05 12:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_polls', '0002_auto_20181005_1206'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswerMultiple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_touched', models.DateTimeField(blank=True, null=True)),
                ('last_touched', models.DateTimeField(auto_now=True)),
                ('count_touched', models.PositiveIntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('question_choice_key', models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(0)])),
                ('poll', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_polls.Poll')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_questions.QuestionMultiple')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAnswerOpen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_touched', models.DateTimeField(blank=True, null=True)),
                ('last_touched', models.DateTimeField(auto_now=True)),
                ('count_touched', models.PositiveIntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('question_text', models.TextField(blank=True, max_length=250, null=True)),
                ('poll', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_polls.Poll')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_questions.QuestionOpen')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAnswerYesOrNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_touched', models.DateTimeField(blank=True, null=True)),
                ('last_touched', models.DateTimeField(auto_now=True)),
                ('count_touched', models.PositiveIntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('question_value', models.IntegerField(default=-1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)])),
                ('question_note', models.TextField(blank=True, max_length=250, null=True)),
                ('poll', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_polls.Poll')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_questions.QuestionYesOrNo')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='useransweryesorno',
            unique_together={('poll', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='useransweropen',
            unique_together={('poll', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='useranswermultiple',
            unique_together={('poll', 'question')},
        ),
    ]
