# Generated by Django 2.0.8 on 2018-10-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user_answers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswermultiple',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='useransweropen',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='useransweryesorno',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
