# Generated by Django 2.0.8 on 2019-01-16 09:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user_answers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswermultiple',
            name='answer_choice_key',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, null=True, size=6),
        ),
    ]
