# Generated by Django 2.0.8 on 2018-10-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user_answers', '0002_auto_20181005_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswermultiple',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useransweropen',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useransweryesorno',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
