# Generated by Django 2.0.8 on 2018-10-05 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user_answers', '0003_auto_20181005_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswermultiple',
            name='active',
        ),
        migrations.RemoveField(
            model_name='useransweropen',
            name='active',
        ),
        migrations.RemoveField(
            model_name='useransweryesorno',
            name='active',
        ),
    ]
