# Generated by Django 2.0.8 on 2018-10-05 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_user_answers', '0004_auto_20181005_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswermultiple',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='useransweropen',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='useransweryesorno',
            name='submitted_by',
        ),
        migrations.AddField(
            model_name='useranswermultiple',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useransweropen',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useransweryesorno',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
