# Generated by Django 2.0.8 on 2018-10-05 14:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_questions', '0005_remove_question_question_videolink'),
        ('app_user_answers', '0005_auto_20181005_1421'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useranswermultiple',
            unique_together={('user', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='useransweropen',
            unique_together={('user', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='useransweryesorno',
            unique_together={('user', 'question')},
        ),
    ]
