# Generated by Django 2.0.8 on 2018-10-08 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user_answers', '0006_auto_20181005_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswermultiple',
            old_name='question_choice_key',
            new_name='anwser_choice_key',
        ),
        migrations.RenameField(
            model_name='useransweropen',
            old_name='question_text',
            new_name='answer_text',
        ),
        migrations.RenameField(
            model_name='useransweryesorno',
            old_name='question_note',
            new_name='answer_note',
        ),
        migrations.RenameField(
            model_name='useransweryesorno',
            old_name='question_value',
            new_name='answer_value',
        ),
    ]
