# Generated by Django 2.0.8 on 2018-10-08 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user_answers', '0007_auto_20181008_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswermultiple',
            old_name='anwser_choice_key',
            new_name='answer_choice_key',
        ),
    ]
