# Generated by Django 2.0.8 on 2018-10-08 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user_answers', '0008_auto_20181008_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswermultiple',
            name='answer_choice_key',
            field=models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
