# Generated by Django 2.0.8 on 2018-10-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_name', models.CharField(max_length=140, unique=True, verbose_name='Umfrage-Titel')),
                ('poll_description', models.TextField(max_length=255, verbose_name='Umfragebeschreibung')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='Push notfications')),
                ('poll_code', models.CharField(blank=True, max_length=7, unique=True, verbose_name='Poll Code')),
            ],
        ),
    ]
