# Generated by Django 2.0.8 on 2018-10-05 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='poll_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['poll_code'], name='app_polls_p_poll_co_3d420a_idx'),
        ),
    ]
