# Generated by Django 2.0.8 on 2018-10-05 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_polls', '0002_auto_20181005_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='poll_creator',
        ),
    ]
