# Generated by Django 2.0.8 on 2019-01-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='year',
            field=models.IntegerField(choices=[(2018, 2018), (2019, 2019), (2020, 2020)], default=2019, verbose_name='Jahr'),
        ),
    ]
