# Generated by Django 2.0.8 on 2020-02-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_challenges', '0002_auto_20190102_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='year',
            field=models.IntegerField(choices=[(2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], default=2020, verbose_name='Jahr'),
        ),
    ]
