# Generated by Django 2.0.8 on 2018-10-05 12:07

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_polls', '0002_auto_20181005_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('question_text', models.TextField(max_length=250)),
                ('question_videolink', models.CharField(blank=True, max_length=150, null=True)),
                ('question_imagelink', models.CharField(blank=True, max_length=150, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='QuestionMultiple',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_questions.Question')),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=150), default=list, null=True, size=4)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
            bases=('app_questions.question',),
        ),
        migrations.CreateModel(
            name='QuestionOpen',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_questions.Question')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
            bases=('app_questions.question',),
        ),
        migrations.CreateModel(
            name='QuestionYesOrNo',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_questions.Question')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
            bases=('app_questions.question',),
        ),
        migrations.AddField(
            model_name='question',
            name='poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_polls.Poll'),
        ),
    ]
