# Generated by Django 2.0.8 on 2018-10-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_questions', '0002_auto_20181005_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.TextField(default='Unknown', max_length=150),
        ),
    ]
