# Generated by Django 2.0.8 on 2018-10-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_questions', '0003_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(default='Unknown', max_length=150),
        ),
    ]
