# Generated by Django 2.0.8 on 2018-10-05 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_questions', '0004_auto_20181005_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_videolink',
        ),
    ]
