# Generated by Django 2.0.8 on 2018-10-05 17:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_questions', '0005_remove_question_question_videolink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmultiple',
            name='options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, max_length=150), default=list, null=True, size=4),
        ),
    ]
