# Generated by Django 2.0.8 on 2019-01-14 07:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_questions', '0010_auto_20181007_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmultiple',
            name='options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=150), default=list, null=True, size=6),
        ),
    ]
