# Generated by Django 2.0.8 on 2018-10-05 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181005_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currentPoll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_polls.Poll'),
        ),
    ]
