# Generated by Django 2.0.8 on 2019-05-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190121_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deviceInfo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='osInfo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
