# Generated by Django 2.0.8 on 2019-05-12 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190512_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='deviceInfo',
            new_name='browserInfo',
        ),
    ]
