# Generated by Django 2.0.8 on 2018-10-06 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_polls', '0003_remove_poll_poll_creator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success_email', models.CharField(default='', max_length=150)),
                ('poll', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_polls.Poll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userpoll',
            unique_together={('user', 'poll')},
        ),
    ]
