# Generated by Django 2.0.8 on 2018-10-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user_polls', '0002_auto_20181006_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpoll',
            name='success_email',
            field=models.EmailField(max_length=254),
        ),
    ]
