# Generated by Django 2.0.8 on 2019-01-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user_polls', '0004_auto_20190102_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpoll',
            name='success_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
