# Generated by Django 2.0.8 on 2019-01-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user_polls', '0005_auto_20190102_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpoll',
            name='success_email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
    ]
